<?php

/*
[SETUP]
#S001 : Filtro 
#S002 : 

*/


// Avisa ao Wordpress para executar a função twentyten_setup()
// quando o 'after_setup_theme' hook roda.
add_action( 'after_setup_theme', 'twentyten_setup' );

if ( ! function_exists( 'twentyten_setup' ) ):

	// Configura os padrões do tema e suporte a algumas funções do wp.
	function twentyten_setup() {

		// Ativa o editor-style.css
		add_editor_style('assets/css/editor-style.css');

		// Ativa a imagem destacada
		add_theme_support( 'post-thumbnails' );

		// Add default posts and comments RSS feed links to head
		add_theme_support( 'automatic-feed-links' );

		// Registra os nav_menus
		register_nav_menus( array(
			'global' => __( 'Navegação Global', 'twentyten' ),
			'local' => __( 'Navegação Local', 'twentyten' ),
		) );

}
endif;


/**
 * Makes some changes to the <title> tag, by filtering the output of wp_title().
 *
 * If we have a site description and we're viewing the home page or a blog posts
 * page (when using a static front page), then we will add the site description.
 *
 * If we're viewing a search result, then we're going to recreate the title entirely.
 * We're going to add page numbers to all titles as well, to the middle of a search
 * result title and the end of all other titles.
 *
 * The site title also gets added to all titles.
 *
 * @since Twenty Ten 1.0
 *
 * @param string $title Title generated by wp_title()
 * @param string $separator The separator passed to wp_title(). Twenty Ten uses a
 * 	vertical bar, "|", as a separator in header.php.
 * @return string The new title, ready for the <title> tag.
 */
function twentyten_filter_wp_title( $title, $separator ) {
	// Don't affect wp_title() calls in feeds.
	if ( is_feed() )
		return $title;

	// The $paged global variable contains the page number of a listing of posts.
	// The $page global variable contains the page number of a single post that is paged.
	// We'll display whichever one applies, if we're not looking at the first page.
	global $paged, $page;

	if ( is_search() ) {
		// If we're a search, let's start over:
		$title = sprintf( __( 'Search results for %s', 'twentyten' ), '"' . get_search_query() . '"' );
		// Add a page number if we're on page 2 or more:
		if ( $paged >= 2 )
			$title .= " $separator " . sprintf( __( 'Page %s', 'twentyten' ), $paged );
		// Add the site name to the end:
		$title .= " $separator " . get_bloginfo( 'name', 'display' );
		// We're done. Let's send the new title back to wp_title():
		return $title;
	}

	// Otherwise, let's start by adding the site name to the end:
	$title .= get_bloginfo( 'name', 'display' );

	// If we have a site description and we're on the home/front page, add the description:
	$site_description = get_bloginfo( 'description', 'display' );
	if ( $site_description && ( is_home() || is_front_page() ) )
		$title .= " $separator " . $site_description;

	// Add a page number if necessary:
	if ( $paged >= 2 || $page >= 2 )
		$title .= " $separator " . sprintf( __( 'Page %s', 'twentyten' ), max( $paged, $page ) );

	// Return the new title to wp_title():
	return $title;
}
add_filter( 'wp_title', 'twentyten_filter_wp_title', 10, 2 );

/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * @since Twenty Ten 1.0
 */
function twentyten_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}
add_filter( 'wp_page_menu_args', 'twentyten_page_menu_args' );


/**
 * Limite do excerpt
 *
 * @since Twenty Ten 1.0
 * @return int
 */
function twentyten_excerpt_length( $length ) {
	return 40;
}
add_filter( 'excerpt_length', 'twentyten_excerpt_length' );

/**
 * Returns a "Continue Reading" link for excerpts
 *
 * @since Twenty Ten 1.0
 * @return string "Continue Reading" link
 */
function twentyten_continue_reading_link() {
	return ' <a href="'. get_permalink() . '">' . __( 'Continue reading <span class="meta-nav">&rarr;</span>', 'twentyten' ) . '</a>';
}

/**
 * Replaces "[...]" (appended to automatically generated excerpts) with an ellipsis and twentyten_continue_reading_link().
 *
 * To override this in a child theme, remove the filter and add your own
 * function tied to the excerpt_more filter hook.
 *
 * @since Twenty Ten 1.0
 * @return string An ellipsis
 */
function twentyten_auto_excerpt_more( $more ) {
	return ' &hellip;' . twentyten_continue_reading_link();
}
add_filter( 'excerpt_more', 'twentyten_auto_excerpt_more' );

/**
 * Adds a pretty "Continue Reading" link to custom post excerpts.
 *
 * To override this link in a child theme, remove the filter and add your own
 * function tied to the get_the_excerpt filter hook.
 *
 * @since Twenty Ten 1.0
 * @return string Excerpt with a pretty "Continue Reading" link
 */
function twentyten_custom_excerpt_more( $output ) {
	if ( has_excerpt() && ! is_attachment() ) {
		$output .= twentyten_continue_reading_link();
	}
	return $output;
}
add_filter( 'get_the_excerpt', 'twentyten_custom_excerpt_more' );

/**
 * Remove inline styles printed when the gallery shortcode is used.
 *
 * Galleries are styled by the theme in Twenty Ten's style.css.
 *
 * @since Twenty Ten 1.0
 * @return string The gallery style filter, with the styles themselves removed.
 */
function twentyten_remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
add_filter( 'gallery_style', 'twentyten_remove_gallery_css' );

if ( ! function_exists( 'twentyten_comment' ) ) :
/**
 * Template for comments and pingbacks.
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own twentyten_comment(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 * @since Twenty Ten 1.0
 */
function twentyten_comment( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
		case '' :
	?>

	<li <?php comment_class(); ?> id="li-comment-<?php comment_ID(); ?>">
		<div id="comment-<?php comment_ID(); ?>">
		<div class="comment-author vcard">
			<?php echo get_avatar( $comment, 64 ); ?>
		</div><!-- .comment-author .vcard -->
		<div class="boxtextocomentario">
			<?php if ( $comment->comment_approved == '0' ) : ?>
				<em><?php _e( 'Seu comentário esta aguardando aprovação.', 'twentyten' ); ?></em>
				<br />
			<?php endif; ?>
			<?php printf( __( '%s', 'twentyten' ), sprintf( '<cite class="fn">%s</cite>', get_comment_author_link() ) ); ?>
			
			<div class="comment-meta commentmetadata"><a href="<?php echo esc_url( get_comment_link( $comment->comment_ID ) ); ?>">
				<?php
					/* translators: 1: date, 2: time */
					printf( __( '%1$s at %2$s', 'twentyten' ), get_comment_date(),  get_comment_time() ); ?></a><?php edit_comment_link( __( '(Edit)', 'twentyten' ), ' ' );
				?>
			</div><!-- .comment-meta .commentmetadata -->
	
			<div class="comment-body"><?php comment_text(); ?></div>
			<!--
			<div class="reply">
				<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
			</div><!-- .reply -->
		
		</div> <!-- .boxtextocomentario -->
		<br class="clear" />
	</div><!-- #comment-##  -->

	<?php
			break;
		case 'pingback'  :
		case 'trackback' :
	?>
	<li class="post pingback">
		<p><?php _e( 'Pingback:', 'twentyten' ); ?> <?php comment_author_link(); ?><?php edit_comment_link( __('(Edit)', 'twentyten'), ' ' ); ?></p>
	<?php
			break;
	endswitch;
}
endif;

/**
 * Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
 *
 * To override twentyten_widgets_init() in a child theme, remove the action hook and add your own
 * function tied to the init hook.
 *
 * @since Twenty Ten 1.0
 * @uses register_sidebar
 */
function twentyten_widgets_init() {
	// Area 1, located at the top of the sidebar.
	register_sidebar( array(
		'name' => __( 'Sidebar', 'twentyten' ),
		'id' => 'sidebar-principal',
		'description' => __( 'Arraste os itens desejados até aqui. ', 'twentyten' ),
		'before_widget' => '<div class="widgetsidebar" id="%1$s">',
		'after_widget' => '</div>',
		'before_title' => '<h2 style="display:none;">',
		'after_title' => '</h2>',
	) );

}

/** Register sidebars by running twentyten_widgets_init() on the widgets_init hook. */
add_action( 'widgets_init', 'twentyten_widgets_init' );


/*
 * Helper function to return the theme option value. If no value has been saved, it returns $default.
 * Needed because options are saved as serialized strings.
 *
 * This code allows the theme to work without errors if the Options Framework plugin has been disabled.
 */
if ( !function_exists( 'of_get_option' ) ) {
function of_get_option($name, $default = false) {
    $optionsframework_settings = get_option('optionsframework');
    // Gets the unique option id
    $option_name = $optionsframework_settings['id'];
    if ( get_option($option_name) ) {
        $options = get_option($option_name);
    }
    if ( isset($options[$name]) ) {
        return $options[$name];
    } else {
        return $default;
    }
}
}



/* Carrega Arquivos JS do tema */
/* ----------------------------------------- */
	add_action( 'wp_print_scripts', 'bigo_load_scripts' );

	function bigo_load_scripts(){

    if (!is_admin()){
              
			// Desregistrando o jquery nativo e registrando o do CDN do Google.
			// wp_deregister_script('jquery');
			// wp_register_script('jquery', '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js', false, '1.10.2');
			wp_enqueue_script('jquery');	

			// Os demais js
			// wp_enqueue_script('smoothwheel', get_template_directory_uri(). '/assets/js/jquery.smoothwheel-ck.js', array('jquery'));
			wp_enqueue_script('jsbootstrap', get_template_directory_uri(). '/assets/js/bootstrap.min.js', array('jquery'));
			wp_enqueue_script('slick', get_template_directory_uri(). '/assets/slick/slick.min.js', array('jquery'));
			wp_enqueue_script('acf-maps', get_template_directory_uri(). '/assets/js/maps.js', array('jquery'));
			wp_enqueue_script('codigo', get_template_directory_uri(). '/assets/js/codigo.js', array('jquery'));
	  }

	}

/* Carrega Scripts/Styles para Lightbox */
/* ----------------------------------------- */
	function twentytwelve_add_lightbox() {
	    wp_enqueue_script( 'fancybox', get_template_directory_uri() . '/assets/lightbox/js/jquery.fancybox.pack.js', array( 'jquery' ), false, true );
	    wp_enqueue_script( 'lightbox', get_template_directory_uri() . '/assets/lightbox/js/lightbox.js', array( 'fancybox' ), false, true );
	    wp_enqueue_style( 'lightbox-style', get_template_directory_uri() . '/assets/lightbox/css/jquery.fancybox.css' );
	}
	add_action( 'wp_enqueue_scripts', 'twentytwelve_add_lightbox' );


/* Carrega Arquivos CSS do tema */
/* ----------------------------------------- */
	function bigo_load_css(){ 

		// Carrega o arquivo em todas as páginas
		wp_enqueue_style( 'slick', get_template_directory_uri() . '/assets/slick/slick.css' );
		wp_enqueue_style( 'slick-theme', get_template_directory_uri() . '/assets/slick/slick-theme.css' );
		wp_enqueue_style( 'fontawesome', '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', false, '4.3.0');
		// wp_enqueue_style( 'hover', get_template_directory_uri() . '/assets/css/hover.css' );

	}
	add_action('wp_enqueue_scripts', 'bigo_load_css');



/* Adiciona editor se usuário for editor no body-class */
/* --------------------------------------------------- */
function role_user_body_class( $classes ) {
	if( current_user_can('editor') ) { $classes .= ' editor'; }
  return trim( $classes );
}
add_filter( 'admin_body_class', 'role_user_body_class' );

function bigo_get_images($size = 'thumbnail') {
  global $post;
  return get_children( array('post_parent' => $post->ID, 'post_status' => 'inherit', 'post_type' => 'attachment', 'post_mime_type' => 'image', 'order' => 'ASC', 'orderby' => 'menu_order') );
}

/* Cria opções de páginas */
/* --------------------------------------------------- */
if( function_exists('acf_add_options_page') ) {
	acf_add_options_page();	
}
/* Cria campo personalizado do logotipo */
/* --------------------------------------------------- */
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_552c19fc1dd7c',
	'title' => 'Logotipo',
	'fields' => array (
		array (
			'key' => 'field_552c1a01a03f6',
			'label' => 'Opções do site',
			'name' => 'logotipo',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;

/* Cria repeater do banner principal para slider */
if( function_exists('register_field_group') ):
register_field_group(array (
	'key' => 'group_552c0e6260dfe',
	'title' => 'Banner',
	'fields' => array (
		array (
			'key' => 'field_552c0e7603fec',
			'label' => 'Slider Principal',
			'name' => 'slider_principal',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Adicionar Novo',
			'sub_fields' => array (
				array (
					'key' => 'field_552c0f8e03fed',
					'label' => 'Imagem',
					'name' => 'imagem_slider',
					'prefix' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'banner-topo',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_552c104903fef',
					'label' => 'Descrição',
					'name' => 'descricao_slider',
					'prefix' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_552c102a03fee',
					'label' => 'Título',
					'name' => 'titulo_slider',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_552c106103ff0',
					'label' => 'Link',
					'name' => 'link_slider',
					'prefix' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;

/* Cria campos de informações */
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array (
	'key' => 'group_55ae4322eeec0',
	'title' => 'Informações',
	'fields' => array (
		array (
			'key' => 'field_55ae44a142a30',
			'label' => 'Redes Sociais',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55ae432d42a2d',
			'label' => 'Redes Sociais',
			'name' => 'sociais_info',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Adicionar novo',
			'sub_fields' => array (
				array (
					'key' => 'field_55ae433d42a2e',
					'label' => 'Ícone',
					'name' => 'icone_info',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => 'fa-facebook',
					'save_format' => 'element',
					'allow_null' => 0,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array (
						'null' => '- Select -',
						'fa-adjust' => ' fa-adjust',
						'fa-adn' => ' fa-adn',
						'fa-align-center' => ' fa-align-center',
						'fa-align-justify' => ' fa-align-justify',
						'fa-align-left' => ' fa-align-left',
						'fa-align-right' => ' fa-align-right',
						'fa-ambulance' => ' fa-ambulance',
						'fa-anchor' => ' fa-anchor',
						'fa-android' => ' fa-android',
						'fa-angellist' => ' fa-angellist',
						'fa-angle-double-down' => ' fa-angle-double-down',
						'fa-angle-double-left' => ' fa-angle-double-left',
						'fa-angle-double-right' => ' fa-angle-double-right',
						'fa-angle-double-up' => ' fa-angle-double-up',
						'fa-angle-down' => ' fa-angle-down',
						'fa-angle-left' => ' fa-angle-left',
						'fa-angle-right' => ' fa-angle-right',
						'fa-angle-up' => ' fa-angle-up',
						'fa-apple' => ' fa-apple',
						'fa-archive' => ' fa-archive',
						'fa-area-chart' => ' fa-area-chart',
						'fa-arrow-circle-down' => ' fa-arrow-circle-down',
						'fa-arrow-circle-left' => ' fa-arrow-circle-left',
						'fa-arrow-circle-o-down' => ' fa-arrow-circle-o-down',
						'fa-arrow-circle-o-left' => ' fa-arrow-circle-o-left',
						'fa-arrow-circle-o-right' => ' fa-arrow-circle-o-right',
						'fa-arrow-circle-o-up' => ' fa-arrow-circle-o-up',
						'fa-arrow-circle-right' => ' fa-arrow-circle-right',
						'fa-arrow-circle-up' => ' fa-arrow-circle-up',
						'fa-arrow-down' => ' fa-arrow-down',
						'fa-arrow-left' => ' fa-arrow-left',
						'fa-arrow-right' => ' fa-arrow-right',
						'fa-arrow-up' => ' fa-arrow-up',
						'fa-arrows' => ' fa-arrows',
						'fa-arrows-alt' => ' fa-arrows-alt',
						'fa-arrows-h' => ' fa-arrows-h',
						'fa-arrows-v' => ' fa-arrows-v',
						'fa-asterisk' => ' fa-asterisk',
						'fa-at' => ' fa-at',
						'fa-backward' => ' fa-backward',
						'fa-ban' => ' fa-ban',
						'fa-bar-chart' => ' fa-bar-chart',
						'fa-barcode' => ' fa-barcode',
						'fa-bars' => ' fa-bars',
						'fa-bed' => ' fa-bed',
						'fa-beer' => ' fa-beer',
						'fa-behance' => ' fa-behance',
						'fa-behance-square' => ' fa-behance-square',
						'fa-bell' => ' fa-bell',
						'fa-bell-o' => ' fa-bell-o',
						'fa-bell-slash' => ' fa-bell-slash',
						'fa-bell-slash-o' => ' fa-bell-slash-o',
						'fa-bicycle' => ' fa-bicycle',
						'fa-binoculars' => ' fa-binoculars',
						'fa-birthday-cake' => ' fa-birthday-cake',
						'fa-bitbucket' => ' fa-bitbucket',
						'fa-bitbucket-square' => ' fa-bitbucket-square',
						'fa-bold' => ' fa-bold',
						'fa-bolt' => ' fa-bolt',
						'fa-bomb' => ' fa-bomb',
						'fa-book' => ' fa-book',
						'fa-bookmark' => ' fa-bookmark',
						'fa-bookmark-o' => ' fa-bookmark-o',
						'fa-briefcase' => ' fa-briefcase',
						'fa-btc' => ' fa-btc',
						'fa-bug' => ' fa-bug',
						'fa-building' => ' fa-building',
						'fa-building-o' => ' fa-building-o',
						'fa-bullhorn' => ' fa-bullhorn',
						'fa-bullseye' => ' fa-bullseye',
						'fa-bus' => ' fa-bus',
						'fa-buysellads' => ' fa-buysellads',
						'fa-calculator' => ' fa-calculator',
						'fa-calendar' => ' fa-calendar',
						'fa-calendar-o' => ' fa-calendar-o',
						'fa-camera' => ' fa-camera',
						'fa-camera-retro' => ' fa-camera-retro',
						'fa-car' => ' fa-car',
						'fa-caret-down' => ' fa-caret-down',
						'fa-caret-left' => ' fa-caret-left',
						'fa-caret-right' => ' fa-caret-right',
						'fa-caret-square-o-down' => ' fa-caret-square-o-down',
						'fa-caret-square-o-left' => ' fa-caret-square-o-left',
						'fa-caret-square-o-right' => ' fa-caret-square-o-right',
						'fa-caret-square-o-up' => ' fa-caret-square-o-up',
						'fa-caret-up' => ' fa-caret-up',
						'fa-cart-arrow-down' => ' fa-cart-arrow-down',
						'fa-cart-plus' => ' fa-cart-plus',
						'fa-cc' => ' fa-cc',
						'fa-cc-amex' => ' fa-cc-amex',
						'fa-cc-discover' => ' fa-cc-discover',
						'fa-cc-mastercard' => ' fa-cc-mastercard',
						'fa-cc-paypal' => ' fa-cc-paypal',
						'fa-cc-stripe' => ' fa-cc-stripe',
						'fa-cc-visa' => ' fa-cc-visa',
						'fa-certificate' => ' fa-certificate',
						'fa-chain-broken' => ' fa-chain-broken',
						'fa-check' => ' fa-check',
						'fa-check-circle' => ' fa-check-circle',
						'fa-check-circle-o' => ' fa-check-circle-o',
						'fa-check-square' => ' fa-check-square',
						'fa-check-square-o' => ' fa-check-square-o',
						'fa-chevron-circle-down' => ' fa-chevron-circle-down',
						'fa-chevron-circle-left' => ' fa-chevron-circle-left',
						'fa-chevron-circle-right' => ' fa-chevron-circle-right',
						'fa-chevron-circle-up' => ' fa-chevron-circle-up',
						'fa-chevron-down' => ' fa-chevron-down',
						'fa-chevron-left' => ' fa-chevron-left',
						'fa-chevron-right' => ' fa-chevron-right',
						'fa-chevron-up' => ' fa-chevron-up',
						'fa-child' => ' fa-child',
						'fa-circle' => ' fa-circle',
						'fa-circle-o' => ' fa-circle-o',
						'fa-circle-o-notch' => ' fa-circle-o-notch',
						'fa-circle-thin' => ' fa-circle-thin',
						'fa-clipboard' => ' fa-clipboard',
						'fa-clock-o' => ' fa-clock-o',
						'fa-cloud' => ' fa-cloud',
						'fa-cloud-download' => ' fa-cloud-download',
						'fa-cloud-upload' => ' fa-cloud-upload',
						'fa-code' => ' fa-code',
						'fa-code-fork' => ' fa-code-fork',
						'fa-codepen' => ' fa-codepen',
						'fa-coffee' => ' fa-coffee',
						'fa-cog' => ' fa-cog',
						'fa-cogs' => ' fa-cogs',
						'fa-columns' => ' fa-columns',
						'fa-comment' => ' fa-comment',
						'fa-comment-o' => ' fa-comment-o',
						'fa-comments' => ' fa-comments',
						'fa-comments-o' => ' fa-comments-o',
						'fa-compass' => ' fa-compass',
						'fa-compress' => ' fa-compress',
						'fa-connectdevelop' => ' fa-connectdevelop',
						'fa-copyright' => ' fa-copyright',
						'fa-credit-card' => ' fa-credit-card',
						'fa-crop' => ' fa-crop',
						'fa-crosshairs' => ' fa-crosshairs',
						'fa-css3' => ' fa-css3',
						'fa-cube' => ' fa-cube',
						'fa-cubes' => ' fa-cubes',
						'fa-cutlery' => ' fa-cutlery',
						'fa-dashcube' => ' fa-dashcube',
						'fa-database' => ' fa-database',
						'fa-delicious' => ' fa-delicious',
						'fa-desktop' => ' fa-desktop',
						'fa-deviantart' => ' fa-deviantart',
						'fa-diamond' => ' fa-diamond',
						'fa-digg' => ' fa-digg',
						'fa-dot-circle-o' => ' fa-dot-circle-o',
						'fa-download' => ' fa-download',
						'fa-dribbble' => ' fa-dribbble',
						'fa-dropbox' => ' fa-dropbox',
						'fa-drupal' => ' fa-drupal',
						'fa-eject' => ' fa-eject',
						'fa-ellipsis-h' => ' fa-ellipsis-h',
						'fa-ellipsis-v' => ' fa-ellipsis-v',
						'fa-empire' => ' fa-empire',
						'fa-envelope' => ' fa-envelope',
						'fa-envelope-o' => ' fa-envelope-o',
						'fa-envelope-square' => ' fa-envelope-square',
						'fa-eraser' => ' fa-eraser',
						'fa-eur' => ' fa-eur',
						'fa-exchange' => ' fa-exchange',
						'fa-exclamation' => ' fa-exclamation',
						'fa-exclamation-circle' => ' fa-exclamation-circle',
						'fa-exclamation-triangle' => ' fa-exclamation-triangle',
						'fa-expand' => ' fa-expand',
						'fa-external-link' => ' fa-external-link',
						'fa-external-link-square' => ' fa-external-link-square',
						'fa-eye' => ' fa-eye',
						'fa-eye-slash' => ' fa-eye-slash',
						'fa-eyedropper' => ' fa-eyedropper',
						'fa-facebook' => ' fa-facebook',
						'fa-facebook-official' => ' fa-facebook-official',
						'fa-facebook-square' => ' fa-facebook-square',
						'fa-fast-backward' => ' fa-fast-backward',
						'fa-fast-forward' => ' fa-fast-forward',
						'fa-fax' => ' fa-fax',
						'fa-female' => ' fa-female',
						'fa-fighter-jet' => ' fa-fighter-jet',
						'fa-file' => ' fa-file',
						'fa-file-archive-o' => ' fa-file-archive-o',
						'fa-file-audio-o' => ' fa-file-audio-o',
						'fa-file-code-o' => ' fa-file-code-o',
						'fa-file-excel-o' => ' fa-file-excel-o',
						'fa-file-image-o' => ' fa-file-image-o',
						'fa-file-o' => ' fa-file-o',
						'fa-file-pdf-o' => ' fa-file-pdf-o',
						'fa-file-powerpoint-o' => ' fa-file-powerpoint-o',
						'fa-file-text' => ' fa-file-text',
						'fa-file-text-o' => ' fa-file-text-o',
						'fa-file-video-o' => ' fa-file-video-o',
						'fa-file-word-o' => ' fa-file-word-o',
						'fa-files-o' => ' fa-files-o',
						'fa-film' => ' fa-film',
						'fa-filter' => ' fa-filter',
						'fa-fire' => ' fa-fire',
						'fa-fire-extinguisher' => ' fa-fire-extinguisher',
						'fa-flag' => ' fa-flag',
						'fa-flag-checkered' => ' fa-flag-checkered',
						'fa-flag-o' => ' fa-flag-o',
						'fa-flask' => ' fa-flask',
						'fa-flickr' => ' fa-flickr',
						'fa-floppy-o' => ' fa-floppy-o',
						'fa-folder' => ' fa-folder',
						'fa-folder-o' => ' fa-folder-o',
						'fa-folder-open' => ' fa-folder-open',
						'fa-folder-open-o' => ' fa-folder-open-o',
						'fa-font' => ' fa-font',
						'fa-forumbee' => ' fa-forumbee',
						'fa-forward' => ' fa-forward',
						'fa-foursquare' => ' fa-foursquare',
						'fa-frown-o' => ' fa-frown-o',
						'fa-futbol-o' => ' fa-futbol-o',
						'fa-gamepad' => ' fa-gamepad',
						'fa-gavel' => ' fa-gavel',
						'fa-gbp' => ' fa-gbp',
						'fa-gift' => ' fa-gift',
						'fa-git' => ' fa-git',
						'fa-git-square' => ' fa-git-square',
						'fa-github' => ' fa-github',
						'fa-github-alt' => ' fa-github-alt',
						'fa-github-square' => ' fa-github-square',
						'fa-glass' => ' fa-glass',
						'fa-globe' => ' fa-globe',
						'fa-google' => ' fa-google',
						'fa-google-plus' => ' fa-google-plus',
						'fa-google-plus-square' => ' fa-google-plus-square',
						'fa-google-wallet' => ' fa-google-wallet',
						'fa-graduation-cap' => ' fa-graduation-cap',
						'fa-gratipay' => ' fa-gratipay',
						'fa-h-square' => ' fa-h-square',
						'fa-hacker-news' => ' fa-hacker-news',
						'fa-hand-o-down' => ' fa-hand-o-down',
						'fa-hand-o-left' => ' fa-hand-o-left',
						'fa-hand-o-right' => ' fa-hand-o-right',
						'fa-hand-o-up' => ' fa-hand-o-up',
						'fa-hdd-o' => ' fa-hdd-o',
						'fa-header' => ' fa-header',
						'fa-headphones' => ' fa-headphones',
						'fa-heart' => ' fa-heart',
						'fa-heart-o' => ' fa-heart-o',
						'fa-heartbeat' => ' fa-heartbeat',
						'fa-history' => ' fa-history',
						'fa-home' => ' fa-home',
						'fa-hospital-o' => ' fa-hospital-o',
						'fa-html5' => ' fa-html5',
						'fa-ils' => ' fa-ils',
						'fa-inbox' => ' fa-inbox',
						'fa-indent' => ' fa-indent',
						'fa-info' => ' fa-info',
						'fa-info-circle' => ' fa-info-circle',
						'fa-inr' => ' fa-inr',
						'fa-instagram' => ' fa-instagram',
						'fa-ioxhost' => ' fa-ioxhost',
						'fa-italic' => ' fa-italic',
						'fa-joomla' => ' fa-joomla',
						'fa-jpy' => ' fa-jpy',
						'fa-jsfiddle' => ' fa-jsfiddle',
						'fa-key' => ' fa-key',
						'fa-keyboard-o' => ' fa-keyboard-o',
						'fa-krw' => ' fa-krw',
						'fa-language' => ' fa-language',
						'fa-laptop' => ' fa-laptop',
						'fa-lastfm' => ' fa-lastfm',
						'fa-lastfm-square' => ' fa-lastfm-square',
						'fa-leaf' => ' fa-leaf',
						'fa-leanpub' => ' fa-leanpub',
						'fa-lemon-o' => ' fa-lemon-o',
						'fa-level-down' => ' fa-level-down',
						'fa-level-up' => ' fa-level-up',
						'fa-life-ring' => ' fa-life-ring',
						'fa-lightbulb-o' => ' fa-lightbulb-o',
						'fa-line-chart' => ' fa-line-chart',
						'fa-link' => ' fa-link',
						'fa-linkedin' => ' fa-linkedin',
						'fa-linkedin-square' => ' fa-linkedin-square',
						'fa-linux' => ' fa-linux',
						'fa-list' => ' fa-list',
						'fa-list-alt' => ' fa-list-alt',
						'fa-list-ol' => ' fa-list-ol',
						'fa-list-ul' => ' fa-list-ul',
						'fa-location-arrow' => ' fa-location-arrow',
						'fa-lock' => ' fa-lock',
						'fa-long-arrow-down' => ' fa-long-arrow-down',
						'fa-long-arrow-left' => ' fa-long-arrow-left',
						'fa-long-arrow-right' => ' fa-long-arrow-right',
						'fa-long-arrow-up' => ' fa-long-arrow-up',
						'fa-magic' => ' fa-magic',
						'fa-magnet' => ' fa-magnet',
						'fa-male' => ' fa-male',
						'fa-map-marker' => ' fa-map-marker',
						'fa-mars' => ' fa-mars',
						'fa-mars-double' => ' fa-mars-double',
						'fa-mars-stroke' => ' fa-mars-stroke',
						'fa-mars-stroke-h' => ' fa-mars-stroke-h',
						'fa-mars-stroke-v' => ' fa-mars-stroke-v',
						'fa-maxcdn' => ' fa-maxcdn',
						'fa-meanpath' => ' fa-meanpath',
						'fa-medium' => ' fa-medium',
						'fa-medkit' => ' fa-medkit',
						'fa-meh-o' => ' fa-meh-o',
						'fa-mercury' => ' fa-mercury',
						'fa-microphone' => ' fa-microphone',
						'fa-microphone-slash' => ' fa-microphone-slash',
						'fa-minus' => ' fa-minus',
						'fa-minus-circle' => ' fa-minus-circle',
						'fa-minus-square' => ' fa-minus-square',
						'fa-minus-square-o' => ' fa-minus-square-o',
						'fa-mobile' => ' fa-mobile',
						'fa-money' => ' fa-money',
						'fa-moon-o' => ' fa-moon-o',
						'fa-motorcycle' => ' fa-motorcycle',
						'fa-music' => ' fa-music',
						'fa-neuter' => ' fa-neuter',
						'fa-newspaper-o' => ' fa-newspaper-o',
						'fa-openid' => ' fa-openid',
						'fa-outdent' => ' fa-outdent',
						'fa-pagelines' => ' fa-pagelines',
						'fa-paint-brush' => ' fa-paint-brush',
						'fa-paper-plane' => ' fa-paper-plane',
						'fa-paper-plane-o' => ' fa-paper-plane-o',
						'fa-paperclip' => ' fa-paperclip',
						'fa-paragraph' => ' fa-paragraph',
						'fa-pause' => ' fa-pause',
						'fa-paw' => ' fa-paw',
						'fa-paypal' => ' fa-paypal',
						'fa-pencil' => ' fa-pencil',
						'fa-pencil-square' => ' fa-pencil-square',
						'fa-pencil-square-o' => ' fa-pencil-square-o',
						'fa-phone' => ' fa-phone',
						'fa-phone-square' => ' fa-phone-square',
						'fa-picture-o' => ' fa-picture-o',
						'fa-pie-chart' => ' fa-pie-chart',
						'fa-pied-piper' => ' fa-pied-piper',
						'fa-pied-piper-alt' => ' fa-pied-piper-alt',
						'fa-pinterest' => ' fa-pinterest',
						'fa-pinterest-p' => ' fa-pinterest-p',
						'fa-pinterest-square' => ' fa-pinterest-square',
						'fa-plane' => ' fa-plane',
						'fa-play' => ' fa-play',
						'fa-play-circle' => ' fa-play-circle',
						'fa-play-circle-o' => ' fa-play-circle-o',
						'fa-plug' => ' fa-plug',
						'fa-plus' => ' fa-plus',
						'fa-plus-circle' => ' fa-plus-circle',
						'fa-plus-square' => ' fa-plus-square',
						'fa-plus-square-o' => ' fa-plus-square-o',
						'fa-power-off' => ' fa-power-off',
						'fa-print' => ' fa-print',
						'fa-puzzle-piece' => ' fa-puzzle-piece',
						'fa-qq' => ' fa-qq',
						'fa-qrcode' => ' fa-qrcode',
						'fa-question' => ' fa-question',
						'fa-question-circle' => ' fa-question-circle',
						'fa-quote-left' => ' fa-quote-left',
						'fa-quote-right' => ' fa-quote-right',
						'fa-random' => ' fa-random',
						'fa-rebel' => ' fa-rebel',
						'fa-recycle' => ' fa-recycle',
						'fa-reddit' => ' fa-reddit',
						'fa-reddit-square' => ' fa-reddit-square',
						'fa-refresh' => ' fa-refresh',
						'fa-renren' => ' fa-renren',
						'fa-repeat' => ' fa-repeat',
						'fa-reply' => ' fa-reply',
						'fa-reply-all' => ' fa-reply-all',
						'fa-retweet' => ' fa-retweet',
						'fa-road' => ' fa-road',
						'fa-rocket' => ' fa-rocket',
						'fa-rss' => ' fa-rss',
						'fa-rss-square' => ' fa-rss-square',
						'fa-rub' => ' fa-rub',
						'fa-scissors' => ' fa-scissors',
						'fa-search' => ' fa-search',
						'fa-search-minus' => ' fa-search-minus',
						'fa-search-plus' => ' fa-search-plus',
						'fa-sellsy' => ' fa-sellsy',
						'fa-server' => ' fa-server',
						'fa-share' => ' fa-share',
						'fa-share-alt' => ' fa-share-alt',
						'fa-share-alt-square' => ' fa-share-alt-square',
						'fa-share-square' => ' fa-share-square',
						'fa-share-square-o' => ' fa-share-square-o',
						'fa-shield' => ' fa-shield',
						'fa-ship' => ' fa-ship',
						'fa-shirtsinbulk' => ' fa-shirtsinbulk',
						'fa-shopping-cart' => ' fa-shopping-cart',
						'fa-sign-in' => ' fa-sign-in',
						'fa-sign-out' => ' fa-sign-out',
						'fa-signal' => ' fa-signal',
						'fa-simplybuilt' => ' fa-simplybuilt',
						'fa-sitemap' => ' fa-sitemap',
						'fa-skyatlas' => ' fa-skyatlas',
						'fa-skype' => ' fa-skype',
						'fa-slack' => ' fa-slack',
						'fa-sliders' => ' fa-sliders',
						'fa-slideshare' => ' fa-slideshare',
						'fa-smile-o' => ' fa-smile-o',
						'fa-sort' => ' fa-sort',
						'fa-sort-alpha-asc' => ' fa-sort-alpha-asc',
						'fa-sort-alpha-desc' => ' fa-sort-alpha-desc',
						'fa-sort-amount-asc' => ' fa-sort-amount-asc',
						'fa-sort-amount-desc' => ' fa-sort-amount-desc',
						'fa-sort-asc' => ' fa-sort-asc',
						'fa-sort-desc' => ' fa-sort-desc',
						'fa-sort-numeric-asc' => ' fa-sort-numeric-asc',
						'fa-sort-numeric-desc' => ' fa-sort-numeric-desc',
						'fa-soundcloud' => ' fa-soundcloud',
						'fa-space-shuttle' => ' fa-space-shuttle',
						'fa-spinner' => ' fa-spinner',
						'fa-spoon' => ' fa-spoon',
						'fa-spotify' => ' fa-spotify',
						'fa-square' => ' fa-square',
						'fa-square-o' => ' fa-square-o',
						'fa-stack-exchange' => ' fa-stack-exchange',
						'fa-stack-overflow' => ' fa-stack-overflow',
						'fa-star' => ' fa-star',
						'fa-star-half' => ' fa-star-half',
						'fa-star-half-o' => ' fa-star-half-o',
						'fa-star-o' => ' fa-star-o',
						'fa-steam' => ' fa-steam',
						'fa-steam-square' => ' fa-steam-square',
						'fa-step-backward' => ' fa-step-backward',
						'fa-step-forward' => ' fa-step-forward',
						'fa-stethoscope' => ' fa-stethoscope',
						'fa-stop' => ' fa-stop',
						'fa-street-view' => ' fa-street-view',
						'fa-strikethrough' => ' fa-strikethrough',
						'fa-stumbleupon' => ' fa-stumbleupon',
						'fa-stumbleupon-circle' => ' fa-stumbleupon-circle',
						'fa-subscript' => ' fa-subscript',
						'fa-subway' => ' fa-subway',
						'fa-suitcase' => ' fa-suitcase',
						'fa-sun-o' => ' fa-sun-o',
						'fa-superscript' => ' fa-superscript',
						'fa-table' => ' fa-table',
						'fa-tablet' => ' fa-tablet',
						'fa-tachometer' => ' fa-tachometer',
						'fa-tag' => ' fa-tag',
						'fa-tags' => ' fa-tags',
						'fa-tasks' => ' fa-tasks',
						'fa-taxi' => ' fa-taxi',
						'fa-tencent-weibo' => ' fa-tencent-weibo',
						'fa-terminal' => ' fa-terminal',
						'fa-text-height' => ' fa-text-height',
						'fa-text-width' => ' fa-text-width',
						'fa-th' => ' fa-th',
						'fa-th-large' => ' fa-th-large',
						'fa-th-list' => ' fa-th-list',
						'fa-thumb-tack' => ' fa-thumb-tack',
						'fa-thumbs-down' => ' fa-thumbs-down',
						'fa-thumbs-o-down' => ' fa-thumbs-o-down',
						'fa-thumbs-o-up' => ' fa-thumbs-o-up',
						'fa-thumbs-up' => ' fa-thumbs-up',
						'fa-ticket' => ' fa-ticket',
						'fa-times' => ' fa-times',
						'fa-times-circle' => ' fa-times-circle',
						'fa-times-circle-o' => ' fa-times-circle-o',
						'fa-tint' => ' fa-tint',
						'fa-toggle-off' => ' fa-toggle-off',
						'fa-toggle-on' => ' fa-toggle-on',
						'fa-train' => ' fa-train',
						'fa-transgender' => ' fa-transgender',
						'fa-transgender-alt' => ' fa-transgender-alt',
						'fa-trash' => ' fa-trash',
						'fa-trash-o' => ' fa-trash-o',
						'fa-tree' => ' fa-tree',
						'fa-trello' => ' fa-trello',
						'fa-trophy' => ' fa-trophy',
						'fa-truck' => ' fa-truck',
						'fa-try' => ' fa-try',
						'fa-tty' => ' fa-tty',
						'fa-tumblr' => ' fa-tumblr',
						'fa-tumblr-square' => ' fa-tumblr-square',
						'fa-twitch' => ' fa-twitch',
						'fa-twitter' => ' fa-twitter',
						'fa-twitter-square' => ' fa-twitter-square',
						'fa-umbrella' => ' fa-umbrella',
						'fa-underline' => ' fa-underline',
						'fa-undo' => ' fa-undo',
						'fa-university' => ' fa-university',
						'fa-unlock' => ' fa-unlock',
						'fa-unlock-alt' => ' fa-unlock-alt',
						'fa-upload' => ' fa-upload',
						'fa-usd' => ' fa-usd',
						'fa-user' => ' fa-user',
						'fa-user-md' => ' fa-user-md',
						'fa-user-plus' => ' fa-user-plus',
						'fa-user-secret' => ' fa-user-secret',
						'fa-user-times' => ' fa-user-times',
						'fa-users' => ' fa-users',
						'fa-venus' => ' fa-venus',
						'fa-venus-double' => ' fa-venus-double',
						'fa-venus-mars' => ' fa-venus-mars',
						'fa-viacoin' => ' fa-viacoin',
						'fa-video-camera' => ' fa-video-camera',
						'fa-vimeo-square' => ' fa-vimeo-square',
						'fa-vine' => ' fa-vine',
						'fa-vk' => ' fa-vk',
						'fa-volume-down' => ' fa-volume-down',
						'fa-volume-off' => ' fa-volume-off',
						'fa-volume-up' => ' fa-volume-up',
						'fa-weibo' => ' fa-weibo',
						'fa-weixin' => ' fa-weixin',
						'fa-whatsapp' => ' fa-whatsapp',
						'fa-wheelchair' => ' fa-wheelchair',
						'fa-wifi' => ' fa-wifi',
						'fa-windows' => ' fa-windows',
						'fa-wordpress' => ' fa-wordpress',
						'fa-wrench' => ' fa-wrench',
						'fa-xing' => ' fa-xing',
						'fa-xing-square' => ' fa-xing-square',
						'fa-yahoo' => ' fa-yahoo',
						'fa-yelp' => ' fa-yelp',
						'fa-youtube' => ' fa-youtube',
						'fa-youtube-play' => ' fa-youtube-play',
						'fa-youtube-square' => ' fa-youtube-square',
					),
				),
				array (
					'key' => 'field_55ae446842a2f',
					'label' => 'Url',
					'name' => 'url_info',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_55ae44b742a31',
			'label' => 'Endereço',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55ae44c242a32',
			'label' => 'Endereço',
			'name' => 'endereco_info',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 70,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55ae494f85fe1',
			'label' => 'Telefone',
			'name' => 'telefone_info',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 30,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55ae44df42a33',
			'label' => 'Mapa',
			'name' => 'mapa_info',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 100,
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => 14,
			'height' => 250,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;